var APIBuilder = require('@axway/api-builder-runtime');
var Model = APIBuilder.createModel('test', {
    "connector": "composite",
    "fields": {
        "overviewUri": {
            "type": "string",
            "required": true,
            "model": "additionalInformation",
            "name": "overviewUri"
        },
        "termsUri": {
            "type": "string",
            "model": "additionalInformation",
            "name": "termsUri"
        },
        "eligibilityUri": {
            "type": "string",
            "model": "additionalInformation",
            "name": "eligibilityUri"
        },
        "feesAndPricingUri": {
            "type": "string",
            "model": "additionalInformation",
            "name": "feesAndPricingUri"
        },
        "bundleUri": {
            "type": "string",
            "model": "additionalInformation",
            "name": "bundleUri"
        },
        "additionalinformation": {
            "model": "product",
            "type": "array"
        }
    },
    "actions": [
        "create",
        "read",
        "update",
        "delete",
        "deleteAll"
    ],
    "metadata": {
        "primarykey": "id",
        "primaryKeyDetails": {
            "autogenerated": true
        },
        "inner_join": [
            {
                "model": "product",
                "join_properties": {
                    "additionalInformation": "bundleUri"
                }
            }
        ]
    }
});
module.exports = Model;